### ISSUE TITLE
Add a .scss for convenience

### ISSUE THREAD

**Issue by franciscop** [tylerlong/katex-build#3]
Following this article: https://github.com/sass/sass/issues/193 I cannot just do this:

```
@import 'katex-build/katex.min.css';
```

Which would be awesome if it worked. So I propose to copy that file with a .scss name just for convenience like this:

```
katex-build/_katex.min.scss
```

In this way we can include it easily in our scss files

**Comment by tylerlong** [comment]
I am not sure whether this is a good idea. This project's purpose is to provide **built** files of the katex project. SCSS also needs to be built in order for the browser to understand.

**Comment by franciscop** [comment]
Since SCSS is a super-set of CSS, a valid .css file will also be a valid .scss file. This is also explained in the [referenced sass issue](https://github.com/sass/sass/issues/193):

> I'd like to hear what is the use case where simply renaming the file to have the .scss extension is markedly more inconvenient to justify this work.

However there's an issue with that, since I'd like to update the katex version if a new version is available but I wouldn't be able to do so seamlessly as also noted in the thread:

> There's a number of cases, but the primary one for me is including third party modules and libraries which have their own css. I would like to use sass to process my own scss files and then compile all css into a single download to the browser.
> [...]
> For example, when ever we need to update a third-party package, I'd have to make sure to rename the css files it provides to .scss. It's a small step, but just another thing that can be forgotten when doing upgrades or missing from a README file when distributing source to others. It's the same reason modifying libraries directly is frowned upon rather than monkey-patching them separately as part of the project source you control.

**Comment by tylerlong** [comment]
Hello @franciscop I don't have much experience with sass, let me ask you a question: 

> I would like to use sass to process my own scss files and then compile all css into a single download to the browser.

Why Isn't sass able to process *.css file since CSS is a sub-set of SCSS? If sass is able to process *.css files, why bother renaming them to *.scss ? Does the file extension matter? What you need to do is to tell your sass processor to take care of both *.css and *.scss files.

I think you should instead send a pull request or issue to the sass project. It's its fault to not allow you to  import a css file.

**Comment by franciscop** [comment]
Exactly, the file extension matters even if the content is the same. That issue from before is discussing this exactly, but it's been opened for many years and doesn't look like it's going to be solved anytime soon.

But you are right, this is not the right place for this fix for scss, I'll make an automatic script to manage it. Thanks for checking the issue!
